In [239]:
import pandas as pd
import math
import numpy as np
import gower

In [240]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
census_income = fetch_ucirepo(id=20) 
  
# data (as pandas dataframes) 
X = census_income.data.features 
y = census_income.data.targets 
  
# variable information 
print(census_income.variables) 

              name     role         type      demographic  \
0              age  Feature      Integer              Age   
1        workclass  Feature  Categorical           Income   
2           fnlwgt  Feature      Integer             None   
3        education  Feature  Categorical  Education Level   
4    education-num  Feature      Integer  Education Level   
5   marital-status  Feature  Categorical            Other   
6       occupation  Feature  Categorical            Other   
7     relationship  Feature  Categorical            Other   
8             race  Feature  Categorical             Race   
9              sex  Feature       Binary              Sex   
10    capital-gain  Feature      Integer             None   
11    capital-loss  Feature      Integer             None   
12  hours-per-week  Feature      Integer             None   
13  native-country  Feature  Categorical            Other   
14          income   Target       Binary           Income   

                       

In [242]:
X

age         workclass  fnlwgt  education  education-num  \
0       39         State-gov   77516  Bachelors             13   
1       50  Self-emp-not-inc   83311  Bachelors             13   
2       38           Private  215646    HS-grad              9   
3       53           Private  234721       11th              7   
4       28           Private  338409  Bachelors             13   
...    ...               ...     ...        ...            ...   
48837   39           Private  215419  Bachelors             13   
48838   64               NaN  321403    HS-grad              9   
48839   38           Private  374983  Bachelors             13   
48840   44           Private   83891  Bachelors             13   
48841   35      Self-emp-inc  182148  Bachelors             13   

           marital-status         occupation    relationship  \
0           Never-married       Adm-clerical   Not-in-family   
1      Married-civ-spouse    Exec-managerial         Husband   
2                Divorced  Handlers-cleaners   Not-in-family   
3      Married-civ-spouse  Handlers-cleaners         Husband   
4      Married-civ-spouse     Prof-specialty            Wife   
...                   ...                ...             ...   
48837            Divorced     Prof-specialty   Not-in-family   
48838             Widowed                NaN  Other-relative   
48839  Married-civ-spouse     Prof-specialty         Husband   
48840            Divorced       Adm-clerical       Own-child   
48841  Married-civ-spouse    Exec-managerial         Husband   

                     race     sex  capital-gain  capital-loss  hours-per-week  \
0                   White    Male          2174             0              40   
1                   White    Male             0             0              13   
2                   White    Male             0             0              40   
3                   Black    Male             0             0              40   
4                   Black  Female             0             0              40   
...                   ...     ...           ...           ...             ...   
48837               White  Female             0             0              36   
48838               Black    Male             0             0              40   
48839               White    Male             0             0              50   
48840  Asian-Pac-Islander    Male          5455             0              40   
48841               White    Male             0             0              60   

      native-country  
0      United-States  
1      United-States  
2      United-States  
3      United-States  
4               Cuba  
...              ...  
48837  United-States  
48838  United-States  
48839  United-States  
48840  United-States  
48841  United-States  

[48842 rows x 14 columns]

In [243]:
X.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loss', 'hours-per-week', 'native-country'],
      dtype='object')

In [244]:
X.age.describe()

count    48842.000000
mean        38.643585
std         13.710510
min         17.000000
25%         28.000000
50%         37.000000
75%         48.000000
max         90.000000
Name: age, dtype: float64

In [245]:
X.head()

age         workclass  fnlwgt  education  education-num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital-gain  capital-loss  hours-per-week native-country  
0          2174             0              40  United-States  
1             0             0              13  United-States  
2             0             0              40  United-States  
3             0             0              40  United-States  
4             0             0              40           Cuba

In [246]:
features = ['age', 'capital-gain', 'education', 'workclass']

In [237]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   age           48842 non-null  int64 
 1   capital-gain  48842 non-null  int64 
 2   education     48842 non-null  object
 3   workclass     47879 non-null  object
dtypes: int64(2), object(2)
memory usage: 1.5+ MB


In [214]:
X.describe()

age  capital-gain
count  48842.000000  48842.000000
mean      38.643585   1079.067626
std       13.710510   7452.019058
min       17.000000      0.000000
25%       28.000000      0.000000
50%       37.000000      0.000000
75%       48.000000      0.000000
max       90.000000  99999.000000

In [247]:
X = X.loc[X['workclass']!='?']

In [248]:
X.dropna(inplace=True)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


In [250]:
X.reset_index(inplace=True)

In [251]:
X

index  age         workclass  fnlwgt  education  education-num  \
0          0   39         State-gov   77516  Bachelors             13   
1          1   50  Self-emp-not-inc   83311  Bachelors             13   
2          2   38           Private  215646    HS-grad              9   
3          3   53           Private  234721       11th              7   
4          4   28           Private  338409  Bachelors             13   
...      ...  ...               ...     ...        ...            ...   
45780  48836   33           Private  245211  Bachelors             13   
45781  48837   39           Private  215419  Bachelors             13   
45782  48839   38           Private  374983  Bachelors             13   
45783  48840   44           Private   83891  Bachelors             13   
45784  48841   35      Self-emp-inc  182148  Bachelors             13   

           marital-status         occupation   relationship  \
0           Never-married       Adm-clerical  Not-in-family   
1      Married-civ-spouse    Exec-managerial        Husband   
2                Divorced  Handlers-cleaners  Not-in-family   
3      Married-civ-spouse  Handlers-cleaners        Husband   
4      Married-civ-spouse     Prof-specialty           Wife   
...                   ...                ...            ...   
45780       Never-married     Prof-specialty      Own-child   
45781            Divorced     Prof-specialty  Not-in-family   
45782  Married-civ-spouse     Prof-specialty        Husband   
45783            Divorced       Adm-clerical      Own-child   
45784  Married-civ-spouse    Exec-managerial        Husband   

                     race     sex  capital-gain  capital-loss  hours-per-week  \
0                   White    Male          2174             0              40   
1                   White    Male             0             0              13   
2                   White    Male             0             0              40   
3                   Black    Male             0             0              40   
4                   Black  Female             0             0              40   
...                   ...     ...           ...           ...             ...   
45780               White    Male             0             0              40   
45781               White  Female             0             0              36   
45782               White    Male             0             0              50   
45783  Asian-Pac-Islander    Male          5455             0              40   
45784               White    Male             0             0              60   

      native-country  
0      United-States  
1      United-States  
2      United-States  
3      United-States  
4               Cuba  
...              ...  
45780  United-States  
45781  United-States  
45782  United-States  
45783  United-States  
45784  United-States  

[45785 rows x 15 columns]

In [222]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46043 entries, 0 to 46042
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   index         46043 non-null  int64 
 1   age           46043 non-null  int64 
 2   capital-gain  46043 non-null  int64 
 3   education     46043 non-null  object
 4   workclass     46043 non-null  object
dtypes: int64(3), object(2)
memory usage: 2.1+ MB


In [252]:
X.iloc[0:1,:]

index  age  workclass  fnlwgt  education  education-num marital-status  \
0      0   39  State-gov   77516  Bachelors             13  Never-married   

     occupation   relationship   race   sex  capital-gain  capital-loss  \
0  Adm-clerical  Not-in-family  White  Male          2174             0   

   hours-per-week native-country  
0              40  United-States

In [254]:
X = X[features]

In [255]:
small_X = X.iloc[0:2,:]

In [256]:
small_X['age'] = small_X['age'].astype(float)

/var/folders/5n/9_pt9s2n7w96mvzm_z6s8q5r0000gn/T/ipykernel_6523/2619125425.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  small_X['age'] = small_X['age'].astype(float)


In [257]:
small_X

age  capital-gain  education         workclass
0  39.0          2174  Bachelors         State-gov
1  50.0             0  Bachelors  Self-emp-not-inc

In [258]:
gower.gower_matrix(np.asarray(small_X),cat_features=[0,0,1,1])  #, cat_features=categorical_features)

array([[0. , 1.5],
       [1.5, 0. ]], dtype=float32)

In [56]:
row1 = X[['age','capital-gain']].iloc[0:2,:].values[0]
row2 = X[['age','capital-gain']].iloc[0:2,:].values[1]

In [59]:
row1 - row2

array([ -11, 2174])

In [57]:
np.sqrt(np.sum((row1 - row2) ** 2))

2174.0278287087312

In [58]:
math.dist(row1, row2)

2174.0278287087312

In [260]:
X.head(5000)

age  capital-gain  education         workclass
0      39          2174  Bachelors         State-gov
1      50             0  Bachelors  Self-emp-not-inc
2      38             0    HS-grad           Private
3      53             0       11th           Private
4      28             0  Bachelors           Private
...   ...           ...        ...               ...
4995   35             0    7th-8th           Private
4996   23             0  Bachelors           Private
4997   25             0  Bachelors           Private
4998   19             0    HS-grad           Private
4999   30             0    Masters           Private

[5000 rows x 4 columns]

In [261]:
gower.gower_matrix(np.asarray(X.head(5000)),cat_features=[0,0,1,1])

array([[0.        , 1.0431063 , 1.0088598 , ..., 1.0533803 , 1.0739282 ,
        1.036257  ],
       [1.0431063 , 0.        , 0.5410959 , ..., 0.5856164 , 0.6061644 ,
        0.5684931 ],
       [1.0088598 , 0.5410959 , 0.        , ..., 0.54452056, 0.5650685 ,
        0.5273973 ],
       ...,
       [1.0533803 , 0.5856164 , 0.54452056, ..., 0.        , 0.5205479 ,
        0.5171233 ],
       [1.0739282 , 0.6061644 , 0.5650685 , ..., 0.5205479 , 0.        ,
        0.5376712 ],
       [1.036257  , 0.5684931 , 0.5273973 , ..., 0.5171233 , 0.5376712 ,
        0.        ]], dtype=float32)

In [28]:
gower_topn_index = gower.gower_topn(X.iloc[0:1,:], X.iloc[:,], n = 10)['index']

In [263]:
X.iloc[gower_topn_index][1:]

age  capital-gain  education  workclass
0      39          2174  Bachelors  State-gov
1043   37             0  Bachelors  State-gov
1234   41             0  Bachelors  State-gov
689    43             0  Bachelors  State-gov
2096   37             0  Bachelors  State-gov
2823   40             0  Bachelors  State-gov
3530   40             0  Bachelors  State-gov
2277   42             0  Bachelors  State-gov
1705   43             0  Bachelors  State-gov
3774   38             0  Bachelors  State-gov

In [30]:
gower_topn_index

array([   0, 1043, 1234,  689, 2096, 2823, 3530, 2277, 1705, 3774])

In [31]:
y.loc[gower_topn_index]

income
0     <=50K
1043   >50K
1234  <=50K
689   <=50K
2096  <=50K
2823  <=50K
3530   >50K
2277  <=50K
1705  <=50K
3774   >50K

In [118]:
y.iloc[gower_topn_index].value_counts()

income
<=50K     8
>50K      2
Name: count, dtype: int64